//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StaticIPAutomationUtility.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_STATICIPAUTOMATIONUTILITY_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDC_BUTTON_ACTIVATE_HOME_IP_SETTINGS 1001
#define IDC_IPADDRESS_HOME_IPADDRESS    1003
#define IDC_IPADDRESS_HOME_SUBNET_MASK  1004
#define IDC_IPADDRESS_HOME_DEFAULT_GATEWAY 1005
#define IDC_IPADDRESS_HOME_PREFERRED_DNS 1006
#define IDC_IPADDRESS_HOME_ALTERNATE_DNS 1007
#define IDC_IPADDRESS_OFFICE_IPADDRESS  1008
#define IDC_IPADDRESS_OFFICE_SUBNET_MASK 1009
#define IDC_IPADDRESS_OFFICE_DEFAULT_GATEWAY 1010
#define IDC_IPADDRESS_OFFICE_PREFERRED_DNS 1011
#define IDC_IPADDRESS_OFFICE_ALTERNATE_DNS 1012
#define IDC_BUTTON_ACTIVATE_HOME_DNS_SETTINGS 1013
#define IDC_BUTTON_ACTIVATE_OFFICE_IP_SETTINGS 1015
#define IDC_BUTTON_ACTIVATE_OFFICE_DNS_SETTINGS 1016
#define IDC_STATUS_HOME                 1017
#define IDC_STATUS_OFFICE               1018
#define IDC_EDIT_LAN_CONNECTION_NAME    1019
#define IDC_STATIC_INPUT_CHECK          1020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
